helmDefaults:
  atomic: true
  createNamespace: true
  cleanupOnFail: true
  timeout: 600
  force: false # MUST BE FALSE. true is broken on helm 3 https://github.com/roboll/helmfile/issues/1176

repositories:
- name: "stable"
  url: "https://kubernetes-charts.storage.googleapis.com/"

releases:
  - name: ingress
    namespace: ingress
    chart: "stable/nginx-ingress"
    installed: true
    values:
      - controller:
          extraArgs:
            enable-ssl-passthrough: ""
          hostNetwork: true
          kind: DaemonSet

  - name: metallb
    namespace: metallb-system
    chart: "stable/metallb"
    installed: true
    values:
      - configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 172.17.0.1-172.17.255.255

  - name: metrics-server
    namespace: kube-system
    chart: "stable/metrics-server"
    installed: true
    values:
      - args:
        - --metric-resolution=60s
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
